---
language: generic

sudo: required
dist: trusty

services:
- docker

install:
- docker run --rm -v $(pwd):/usr/src/app tomasbasham/protoc:3.6.1-go -I ./proto --go_out=plugins=grpc:. todo.proto
- docker build -t todo --target builder .

script:
- docker run --rm todo golint -set_exit_status ./...
- docker run --rm todo go vet ./...
- docker run --rm todo go test ./...

notifications:
  email: false
