# Default values for blunderlist-todo.
# Declare variables to be passed into your templates.

replicaCount: 2

image:
  repository: eu.gcr.io/blunderlist/todo
  tag: stable
  pullPolicy: IfNotPresent

nameOverride: ""
fullnameOverride: ""

service:
  type: ClusterIP
  port: 50051

database:
  name: todo
  user: todo
