apiVersion: v1
kind: Service
metadata:
  name: {{ include "todo.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "todo.name" . }}
    helm.sh/chart: {{ include "todo.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  ports:
  - port: {{ .Values.service.port }}
    targetPort: proxy
    protocol: TCP
    name: http2
  selector:
    app.kubernetes.io/name: {{ include "todo.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    serving: "true"
